language: ruby
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++-4.9-dev
  - sudo apt-get install -qq g++-4.9
  - export CXX="g++-4.9" CC="gcc-4.9"
rvm:
#  - 1.9.3
  - 2.0.0-p247
#  - 2.1.0
#  - 2.2.0
branches:
  only:
    - master
