// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package com.indigobio.test;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EverythingOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 f_int32 = 1;
    /**
     * <code>required int32 f_int32 = 1;</code>
     */
    boolean hasFInt32();
    /**
     * <code>required int32 f_int32 = 1;</code>
     */
    int getFInt32();

    // required int64 f_int64 = 2;
    /**
     * <code>required int64 f_int64 = 2;</code>
     */
    boolean hasFInt64();
    /**
     * <code>required int64 f_int64 = 2;</code>
     */
    long getFInt64();

    // required uint32 f_uint32 = 3;
    /**
     * <code>required uint32 f_uint32 = 3;</code>
     */
    boolean hasFUint32();
    /**
     * <code>required uint32 f_uint32 = 3;</code>
     */
    int getFUint32();

    // required uint64 f_uint64 = 4;
    /**
     * <code>required uint64 f_uint64 = 4;</code>
     */
    boolean hasFUint64();
    /**
     * <code>required uint64 f_uint64 = 4;</code>
     */
    long getFUint64();
  }
  /**
   * Protobuf type {@code com.indigobio.test.Everything}
   */
  public static final class Everything extends
      com.google.protobuf.GeneratedMessage
      implements EverythingOrBuilder {
    // Use Everything.newBuilder() to construct.
    private Everything(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Everything(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Everything defaultInstance;
    public static Everything getDefaultInstance() {
      return defaultInstance;
    }

    public Everything getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Everything(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              fInt32_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fInt64_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              fUint32_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              fUint64_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.indigobio.test.Test.internal_static_com_indigobio_test_Everything_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.indigobio.test.Test.internal_static_com_indigobio_test_Everything_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.indigobio.test.Test.Everything.class, com.indigobio.test.Test.Everything.Builder.class);
    }

    public static com.google.protobuf.Parser<Everything> PARSER =
        new com.google.protobuf.AbstractParser<Everything>() {
      public Everything parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Everything(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Everything> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 f_int32 = 1;
    public static final int F_INT32_FIELD_NUMBER = 1;
    private int fInt32_;
    /**
     * <code>required int32 f_int32 = 1;</code>
     */
    public boolean hasFInt32() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 f_int32 = 1;</code>
     */
    public int getFInt32() {
      return fInt32_;
    }

    // required int64 f_int64 = 2;
    public static final int F_INT64_FIELD_NUMBER = 2;
    private long fInt64_;
    /**
     * <code>required int64 f_int64 = 2;</code>
     */
    public boolean hasFInt64() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 f_int64 = 2;</code>
     */
    public long getFInt64() {
      return fInt64_;
    }

    // required uint32 f_uint32 = 3;
    public static final int F_UINT32_FIELD_NUMBER = 3;
    private int fUint32_;
    /**
     * <code>required uint32 f_uint32 = 3;</code>
     */
    public boolean hasFUint32() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 f_uint32 = 3;</code>
     */
    public int getFUint32() {
      return fUint32_;
    }

    // required uint64 f_uint64 = 4;
    public static final int F_UINT64_FIELD_NUMBER = 4;
    private long fUint64_;
    /**
     * <code>required uint64 f_uint64 = 4;</code>
     */
    public boolean hasFUint64() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint64 f_uint64 = 4;</code>
     */
    public long getFUint64() {
      return fUint64_;
    }

    private void initFields() {
      fInt32_ = 0;
      fInt64_ = 0L;
      fUint32_ = 0;
      fUint64_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasFInt32()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFInt64()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFUint32()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFUint64()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, fInt32_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, fInt64_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, fUint32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, fUint64_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, fInt32_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, fInt64_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, fUint32_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, fUint64_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.indigobio.test.Test.Everything parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indigobio.test.Test.Everything parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indigobio.test.Test.Everything parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.indigobio.test.Test.Everything parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.indigobio.test.Test.Everything parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.indigobio.test.Test.Everything parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.indigobio.test.Test.Everything parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.indigobio.test.Test.Everything parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.indigobio.test.Test.Everything parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.indigobio.test.Test.Everything parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.indigobio.test.Test.Everything prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.indigobio.test.Everything}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.indigobio.test.Test.EverythingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.indigobio.test.Test.internal_static_com_indigobio_test_Everything_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.indigobio.test.Test.internal_static_com_indigobio_test_Everything_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.indigobio.test.Test.Everything.class, com.indigobio.test.Test.Everything.Builder.class);
      }

      // Construct using com.indigobio.test.Test.Everything.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        fInt32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        fInt64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        fUint32_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        fUint64_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.indigobio.test.Test.internal_static_com_indigobio_test_Everything_descriptor;
      }

      public com.indigobio.test.Test.Everything getDefaultInstanceForType() {
        return com.indigobio.test.Test.Everything.getDefaultInstance();
      }

      public com.indigobio.test.Test.Everything build() {
        com.indigobio.test.Test.Everything result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.indigobio.test.Test.Everything buildPartial() {
        com.indigobio.test.Test.Everything result = new com.indigobio.test.Test.Everything(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.fInt32_ = fInt32_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fInt64_ = fInt64_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fUint32_ = fUint32_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fUint64_ = fUint64_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.indigobio.test.Test.Everything) {
          return mergeFrom((com.indigobio.test.Test.Everything)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.indigobio.test.Test.Everything other) {
        if (other == com.indigobio.test.Test.Everything.getDefaultInstance()) return this;
        if (other.hasFInt32()) {
          setFInt32(other.getFInt32());
        }
        if (other.hasFInt64()) {
          setFInt64(other.getFInt64());
        }
        if (other.hasFUint32()) {
          setFUint32(other.getFUint32());
        }
        if (other.hasFUint64()) {
          setFUint64(other.getFUint64());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasFInt32()) {
          
          return false;
        }
        if (!hasFInt64()) {
          
          return false;
        }
        if (!hasFUint32()) {
          
          return false;
        }
        if (!hasFUint64()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.indigobio.test.Test.Everything parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.indigobio.test.Test.Everything) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 f_int32 = 1;
      private int fInt32_ ;
      /**
       * <code>required int32 f_int32 = 1;</code>
       */
      public boolean hasFInt32() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 f_int32 = 1;</code>
       */
      public int getFInt32() {
        return fInt32_;
      }
      /**
       * <code>required int32 f_int32 = 1;</code>
       */
      public Builder setFInt32(int value) {
        bitField0_ |= 0x00000001;
        fInt32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 f_int32 = 1;</code>
       */
      public Builder clearFInt32() {
        bitField0_ = (bitField0_ & ~0x00000001);
        fInt32_ = 0;
        onChanged();
        return this;
      }

      // required int64 f_int64 = 2;
      private long fInt64_ ;
      /**
       * <code>required int64 f_int64 = 2;</code>
       */
      public boolean hasFInt64() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 f_int64 = 2;</code>
       */
      public long getFInt64() {
        return fInt64_;
      }
      /**
       * <code>required int64 f_int64 = 2;</code>
       */
      public Builder setFInt64(long value) {
        bitField0_ |= 0x00000002;
        fInt64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 f_int64 = 2;</code>
       */
      public Builder clearFInt64() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fInt64_ = 0L;
        onChanged();
        return this;
      }

      // required uint32 f_uint32 = 3;
      private int fUint32_ ;
      /**
       * <code>required uint32 f_uint32 = 3;</code>
       */
      public boolean hasFUint32() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint32 f_uint32 = 3;</code>
       */
      public int getFUint32() {
        return fUint32_;
      }
      /**
       * <code>required uint32 f_uint32 = 3;</code>
       */
      public Builder setFUint32(int value) {
        bitField0_ |= 0x00000004;
        fUint32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 f_uint32 = 3;</code>
       */
      public Builder clearFUint32() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fUint32_ = 0;
        onChanged();
        return this;
      }

      // required uint64 f_uint64 = 4;
      private long fUint64_ ;
      /**
       * <code>required uint64 f_uint64 = 4;</code>
       */
      public boolean hasFUint64() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint64 f_uint64 = 4;</code>
       */
      public long getFUint64() {
        return fUint64_;
      }
      /**
       * <code>required uint64 f_uint64 = 4;</code>
       */
      public Builder setFUint64(long value) {
        bitField0_ |= 0x00000008;
        fUint64_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 f_uint64 = 4;</code>
       */
      public Builder clearFUint64() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fUint64_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.indigobio.test.Everything)
    }

    static {
      defaultInstance = new Everything(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.indigobio.test.Everything)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_indigobio_test_Everything_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_indigobio_test_Everything_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\022\022com.indigobio.test\"R\n\nEver" +
      "ything\022\017\n\007f_int32\030\001 \002(\005\022\017\n\007f_int64\030\002 \002(\003" +
      "\022\020\n\010f_uint32\030\003 \002(\r\022\020\n\010f_uint64\030\004 \002(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_indigobio_test_Everything_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_indigobio_test_Everything_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_indigobio_test_Everything_descriptor,
              new java.lang.String[] { "FInt32", "FInt64", "FUint32", "FUint64", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
